/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "EKS-Scaler-Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "KarpenterCPU": {
      "architectures": any
      "arn": string
      "codeSha256": string
      "codeSigningConfigArn": string
      "deadLetterConfig": any
      "description": string
      "environment": any
      "ephemeralStorages": any
      "fileSystemConfigs": any
      "functionName": string
      "handler": string
      "id": string
      "imageUri": string
      "invokeArn": string
      "kmsKeyArn": string
      "lastModified": string
      "layers": any
      "loggingConfigs": any
      "memorySize": number
      "qualifiedArn": string
      "qualifiedInvokeArn": string
      "reservedConcurrentExecutions": number
      "role": string
      "runtime": string
      "signingJobArn": string
      "signingProfileVersionArn": string
      "sourceCodeHash": string
      "sourceCodeSize": number
      "tags": {
        "lambda:createdBy": string
      }
      "timeout": number
      "tracingConfig": {
        "mode": string
      }
      "type": "sst.sst.Linkable"
      "version": string
      "vpcConfig": any
    }
    "TerminateEc2": {
      "architectures": any
      "arn": string
      "codeSha256": string
      "codeSigningConfigArn": string
      "deadLetterConfig": any
      "description": string
      "environment": any
      "ephemeralStorages": any
      "fileSystemConfigs": any
      "functionName": string
      "handler": string
      "id": string
      "imageUri": string
      "invokeArn": string
      "kmsKeyArn": string
      "lastModified": string
      "layers": any
      "loggingConfigs": any
      "memorySize": number
      "qualifiedArn": string
      "qualifiedInvokeArn": string
      "reservedConcurrentExecutions": number
      "role": string
      "runtime": string
      "signingJobArn": string
      "signingProfileVersionArn": string
      "sourceCodeHash": string
      "sourceCodeSize": number
      "tags": {
      }
      "timeout": number
      "tracingConfig": {
        "mode": string
      }
      "type": "sst.sst.Linkable"
      "version": string
      "vpcConfig": any
    }
    "eksScalerWebClient": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}