[package]
name = "ec2"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.14.0"
aws-config = "1.5.14"
aws-sdk-ec2 = "1.102.0"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.135"
